### ISSUE TITLE
Website: page about ftHAT cases broken

### ISSUE THREAD

**Issue by heuer** [ftCommunity/tx-pi#67]
Due to the removal of the ftHAT PNG and STL files (was this necessary, acc. to @PeterDHabermehl they can be used / the license is similar to the other files) the website shows broken images:

<https://tx-pi.de/en/cases/hats/tx-pi-hat/>

Solution: 
* either re-add the files
* modify the website: https://github.com/ftCommunity/tx-pi/blob/master/website/templates/cases_hats_tx_pi_hat_de.html and https://github.com/ftCommunity/tx-pi/blob/master/website/templates/cases_hats_tx_pi_hat_en.html

I'd prefer the 1st option.

**Comment by PeterDHabermehl** [comment]
Who did remove them?As far as I am concerned, they can and should be uploaded again!I would just recommend to clarify the status of all materials provided on the pages and add license information accordingly.-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 13.12.22, 09:18 schrieb Lars ***@***.***>:

   
  Due to the removal of the ftHAT PNG and STL files (was this necessary, acc. to @PeterDHabermehl they can be used / the license is similar to the other files) the website shows broken images: 
  https://tx-pi.de/en/cases/hats/tx-pi-hat/ 
  Solution: 
   
   either re-add the files 
   modify the website: https://github.com/ftCommunity/tx-pi/blob/master/website/templates/cases_hats_tx_pi_hat_de.html and https://github.com/ftCommunity/tx-pi/blob/master/website/templates/cases_hats_tx_pi_hat_en.html 
   
  I'd prefer the 1st option.

**Comment by harbaum** [comment]
I was busy the last few days and have been notified that I violate some Copyright by distributing those files. So I removed them to avoid further discussions until this is clarified.

**Comment by PeterDHabermehl** [comment]
Apologies from my side, I confirm that whatever I continued may well be licensed under CC BY ***@***.*** thank you for your efforts to clarify the situation and... nice to see some life sign from you...-- Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 13.12.22, 18:32 schrieb Lars ***@***.***>:

   
  It all looks like a misunderstanding. 
  If you both confirm to me that the files fall under CC BY 4.0 (or tell me the right license), I'd be happy to add appropriate notices to the website and README files and we can close this issue.

**Comment by harbaum** [comment]
Sounds good to me.
